apiVersion: batch/v1
kind: Job
metadata:
  name: cloudagent
spec:
  template:
    metadata:
      name: cloudagent-pod
    spec:
      containers:
      - name: cloudagent
        image: ghcr.io/timdesi/cloudagent:latest
        env:
        - name: FOO
          value: "Hello from the environment"
        - name: CONNECTION_STRING
          value: "**********"
      restartPolicy: Never
