apiVersion: batch/v1
kind: Job
metadata:
  name: cloudagent
spec:
  template:
    metadata:
      name: cloudagent-pod
    spec:
      containers:
      - name: cloudagent
        image: ghcr.io/timdesi/cloudagent:latest
        env:
        - name: FOO
          value: "Hello from the environment"
        - name: CONNECTION_STRING
          value: "HostName=swdc-euwe-dev-ls-001-iot.azure-devices.net;DeviceId=sdv-sofia-dev-3;SharedAccessKey=+cLx1E8FCCSQvTIhQZtD0IAy2LwQ/mYR2sLDx5Sj1M0="
        - name: LOCAL_ADDRESS
          value: tcp://192.168.64.1:1883
      restartPolicy: Never
